### ISSUE TITLE
React Project Setup Checklist:

### ISSUE THREAD

**Issue by DevAniela** [DevAniela/wish-bridge#1]
- [ ] Set up React project
- [ ] Create intro-container with short description explaining the app's purpose and functionality
- [ ] Create a section for user reviews and stories
- [ ] Create individual components for different parts of the application inside 'src' directory (Header.js, WishMakerForm.js, WishList.js, Wish.js, App.js)
- [ ] Move HTML structure into the components
- [ ] Convert HTML to JSX
- [ ] Implement components
- [ ] Style components
- [ ] Find a more suitable aesthetic
- [ ] Install dependencies
- [ ] Add ARIA attributes to improve accessibility
- [ ] Run application
